---
driver_plugin: vagrant

provisioner:
  name: chef_solo

platforms:
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04

suites:
- name: default
  run_list: ["recipe[fake]"]
  attributes: {}
  provisioner:
    solo_rb:
      log_location: /var/log/chef-solo.log
